---
- name: Reboot the remote host
  hosts: all
  become: true
  tasks:
    - name: Reboot the remote hosts
      ansible.builtin.reboot:
        pre_reboot_delay: 5
        post_reboot_delay: 10
        msg : "Rebooted by Ansible "
        test_command: "whoami"
