---
- name: Download the file
  hosts: all
  become: false
  vars:
    myurl: "https://releases.ansible.com/ansible/ansible-2.9.25.tar.gz"
    mycrc: "sha256:https://releases.ansible.com/ansible/ansible-2.9.25.tar.gz.sha"
    mydest: "/root/example"
  tasks:
    - name: Download the file
      ansible.builtin.get_url:
        url: "{{ myurl }}"
        checksum: "{{ mycrc }}"
        dest: "{{ mydest }}"
        mode: "0644"