---
- name: Creating a user
  hosts: all
  become: true
  vars:
    myuser: "example"
    tasks:
      - name: Creating a user
        ansible.builtin.user:
          name: "{{ myuser }}"
          state: present
          password_lock: false
          shell: "/bin/bash"