---
- name: Directory exists
  hosts: all
  become: false
  vars:
    directory: "/tmp"
tasks:
    - name: Check if directory exists
      ansible.builtin.stat:
        path: "{{ directory }}"
      register: dir_to_check
- name: Directory found
      ansible.builtin.debug:
        msg: "Directory {{directory}} is present"
      when: dir_to_check.stat.isdir is defined and dir_to_check.stat.isdir
