---
- name: Creating a user
  hosts: all
  become: true
  vars:
    myuser: "example"
  tasks:
    - name: Removing a user
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password_lock: true
        shell: "/sbin/nologin"