---
- name: Change user password
  hosts: all
  become: true
  vars:
    myuser: "example"
    mypassword: "password"
  tasks:
    - name: Changeing user password
      ansible.builtin.user:
        name: "{{ myuser }}"
        state: present
        password: "{ { mypassword | password_hash('sha512') } }"